set go-=T
set bg=dark
if &background == "dark"
    hi normal guibg=black
    set transp=8
endif
:colorscheme darkz
set lines=65 columns=185
"set guifont=DroidSansMono:h12
set guifont=DejaVuSansMono:h13
set transparency=5

"No blinking for the cursor
set gcr=a:blinkon0
