" source ~/.vim/autotag.vim
" Change swap file directory
set directory=/tmp

" Use comma instead of \ for leader
:let mapleader = ","

set grepprg=ack
set grepformat=%f:%l:%c:%m

set nocompatible
set hidden
set ts=2
set sw=2
set sts=2
set ignorecase
set smartcase
set autoindent
set smartindent
"set expandtab
"set smarttab

:filetype on
:filetype plugin on
:filetype indent on

:syntax on
" Always show the statusline
set laststatus=2

set nowrap
set wildmenu
set wildchar=<Tab> wildmenu wildmode=full

" Line numbers
set nu

" Visual bell
set vb

" Highlight search results
set hlsearch
set incsearch " Incrementally

" Less stingy history
set history=1000

" Title in xterm
set title

" More context for cursor
set scrolloff=3

" Faster viewport scrolling
nnoremap <C-e> 2<C-e>
nnoremap <C-y> 2<C-y>

set statusline=%<%f\ %h%m%r%=%-14.(%l,%c%V%)\ %p%%

:colorscheme darkz

" 'e'dit 'v'imrc)
nmap <silent> ,ev :e $MYVIMRC<CR>
" 's'ource 'v'imrc)
nmap <silent> ,sv :so $MYVIMRC<CR>

" Remove trailing whitespace
:nnoremap <silent> <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>

" Show trailing whitespace
set listchars=tab:>-,trail:·,eol:$
nmap <silent> <leader>s :set nolist!<CR>

" 'e'dit 'v'imrc)
nmap <silent> ,ev :e $MYVIMRC<CR>
" 's'ource 'v'imrc)
nmap <silent> ,sv :so $MYVIMRC<CR>

" cd to the directory containing the file in the buffer
nmap ,cd :lcd %:h

" map FuzzyFinderTextMate
let g:fuzzy_ignore = "*.log,*.png,*.jpg,vendor/**,"
let g:fuzzy_matching_limit = 70

map <leader>f :FuzzyFinderTextMate<CR>
map <leader>b :FuzzyFinderBuffer<CR>
" map <leader>r :FuzzyFinderTextMateRefreshFiles<CR>

map <leader>d :execute 'NERDTreeToggle ' . getcwd()<CR>

" For python, modify for Ruby
autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
autocmd BufWritePre *.py :%s/\s\+$//e

" Project
:let g:proj_flags="imstvcg"

" Emacs moving in insert mode
imap <C-b> <Left>
omap <C-b> <Left>
imap <C-f> <Right>
omap <C-f> <Right>
imap <C-p> <Up>
omap <C-p> <Up>
imap <C-n> <Down>
omap <C-n> <Down>
inoremap <M-f> <C-o>e<Right>
onoremap <M-f> e<Right>
inoremap <M-b> <C-Left>
onoremap <M-b> <C-Left>
imap <C-a> <Home>
omap <C-a> <Home>
imap <C-e> <End>
omap <C-e> <End>
inoremap <C-d> <Del>
inoremap <silent> <C-k> <C-r>=<SID>KillLine()<CR>


" allow command line editing like emacs
cnoremap <C-A>      <Home>
cnoremap <C-B>      <Left>
cnoremap <C-E>      <End>
cnoremap <C-F>      <Right>
cnoremap <C-N>      <End>
cnoremap <C-P>      <Up>
cnoremap <ESC>b     <S-Left>
cnoremap <ESC><C-B> <S-Left>
cnoremap <ESC>f     <S-Right>
cnoremap <ESC><C-F> <S-Right>
cnoremap <ESC><C-H> <C-W>

vmap <C-x> ylpr

" Insert a new line with shift-enter in insert mode
map <S-Enter> o<Esc>

set pastetoggle=<F2>

au BufNewFile,BufRead *.js,.javascript,.es setf js
let tlist_js_settings = 'js;f:function'

"au BufNewFile,BufRead *.ejs let b:swill = "html" | set ft=swill

map <C-t><up> :tabnew<cr>
map <C-t><down> :tabclose<cr>
map <C-t><left> :tabprevious<cr>
map <C-t><right> :tabnext<cr>

" Windows
" Move the cursor to the window left of the current one
noremap <silent> ,h :wincmd h<cr>
" Move the cursor to the window below the current one
noremap <silent> ,j :wincmd j<cr>
" Move the cursor to the window above the current one
noremap <silent> ,k :wincmd k<cr>
" Move the cursor to the window right of the current one
noremap <silent> ,l :wincmd l<cr>
" Close the window below this one
noremap <silent> ,cj :wincmd j<cr>:close<cr>
" Close the window above this one
noremap <silent> ,ck :wincmd k<cr>:close<cr>
" Close the window to the left of this one
noremap <silent> ,ch :wincmd h<cr>:close<cr>
" Close the window to the right of this one
noremap <silent> ,cl :wincmd l<cr>:close<cr>
" Close the current window
noremap <silent> ,cc :close<cr>
" Move the current window to the right of the main Vim window
noremap <silent> ,ml <C-W>L
" Move the current window to the top of the main Vim window
noremap <silent> ,mk <C-W>K
" Move the current window to the left of the main Vim window
noremap <silent> ,mh <C-W>H
" Move the current window to the bottom of the main Vim window
noremap <silent> ,mj <C-W>J
" Resizing
" noremap <silent> <C-F9>  :vertical resize -10<CR>
" noremap <silent> <C-F10> :resize +10<CR>
" noremap <silent> <C-F11> :resize -10<CR>
" noremap <silent> <C-F12> :vertical resize +10<CR>

" Highlight all instances of the current word under the cursor
nmap <silent>T :setl hls<CR>:let @/="<C-r><C-w>"<CR>

